dataset:
  test_path: data/processed/gue_human_tf_4/test.jsonl
  train_path: data/processed/gue_human_tf_4/train.jsonl
  valid_path: data/processed/gue_human_tf_4/valid.jsonl
env:
  backbone_name: zhihan1996/DNABERT-2-117M
  checkpoint_path: results/baselines/dnabert2_bpe_finetuned_human_tf_4/best_model.pt
  hidden_size: 768
  max_length: 512
  num_labels: 2
project_name: StridedPooling_human_tf_4
seed: 42
stride_pooling:
  stride: 4
  trainable_encoder_layers: 2
training:
  batch_size: 16
  learning_rate: 1.0e-05
  num_epochs: 5
  output_dir: results/baselines/stride_pooling_human_tf_4
