project_name: GumbelSegmenterPromoter
seed: 42

dataset:
  train_path: data/processed/gue_promoter/train.jsonl
  valid_path: data/processed/gue_promoter/valid.jsonl
  test_path:  data/processed/gue_promoter/test.jsonl

env:
  backbone_name: zhihan1996/DNABERT-2-117M
  checkpoint_path: results/baselines/dnabert2_bpe/best_model.pt
  hidden_size: 768
  num_labels: 2
  max_length: 512

gumbel:
  trainable_encoder_layers: 2
  initial_temperature: 1.0
  min_temperature: 0.1
  anneal_rate: 0.0003
  beta: 0.02

training:
  batch_size: 16
  learning_rate: 0.00001
  num_epochs: 5
  output_dir: results/baselines/gumbel_segmenter_promoter
